blank_issues_enabled: false
contact_links:
  - name: 💬 Preguntas o discusiones
    url: https://github.com/Robbyfuu/vscode-pseint/discussions
    about: Para preguntas generales o discusión, abrí un Discussion en lugar de un issue.
